language: node_js
env:
  - CXX=g++-4.8
node_js:
  - "0.12"
  - "4.3"
  - "4.4"
  - "5.10"
  - "5.11"
  - "6.2"
  - "6.3"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
